project:
  type: website
  output-dir: docs  

website:
  title: "London SDE/AIC Technical Documentation"
  navbar:
    background: secondary
  sidebar: 
    style: "docked"
    search: false
    contents:
      - section: "MAIN"
        contents: 
          - href: index.qmd
            text: Home
      - section: "COMMON DATA MODEL"
        contents: 
          - href: pages/data_model/cdm_person.qmd
            text: PERSON
          - href: pages/data_model/cdm_condition_occurrence.qmd
            text: CONDITION OCCURRENCE            
                     
format:
  html:
    theme: zephyr
    mermaid:
      theme: neutral
